// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.helpdesk.v1.model;
import com.lark.oapi.core.response.EmptyData;
import com.lark.oapi.service.helpdesk.v1.enums.*;
import com.google.gson.annotations.SerializedName;
import com.lark.oapi.core.annotation.Body;
import com.lark.oapi.core.annotation.Path;
import com.lark.oapi.core.annotation.Query;
import java.io.File;
import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import com.lark.oapi.core.utils.Strings;
import com.lark.oapi.core.response.BaseResponse;
public class ListTicketMessageReq {
    @Query
    @SerializedName("time_start")
    private Integer timeStart;
    @Query
    @SerializedName("time_end")
    private Integer timeEnd;
    @Query
    @SerializedName("page")
    private Integer page;
    @Query
    @SerializedName("page_size")
    private Integer pageSize;
    public Integer getTimeStart() {
        return this.timeStart;
    }

    public void setTimeStart(Integer timeStart) {
        this.timeStart = timeStart;
    }

    public Integer getTimeEnd() {
        return this.timeEnd;
    }

    public void setTimeEnd(Integer timeEnd) {
        this.timeEnd = timeEnd;
    }

    public Integer getPage() {
        return this.page;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public Integer getPageSize() {
        return this.pageSize;
    }

    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    @Path
    @SerializedName("ticket_id")
    private String ticketId;
    public String getTicketId() {
        return this.ticketId;
    }

    public void setTicketId(String ticketId) {
        this.ticketId = ticketId;
    }


// builder 开始
  public ListTicketMessageReq(){}

  public ListTicketMessageReq(Builder builder){
       this.timeStart = builder.timeStart;
       this.timeEnd = builder.timeEnd;
       this.page = builder.page;
       this.pageSize = builder.pageSize;
       this.ticketId = builder.ticketId;
  }

    public static class Builder {
        private Integer timeStart;
        private Integer timeEnd;
        private Integer page;
        private Integer pageSize;
    
           public Builder timeStart(Integer timeStart) {
                this.timeStart = timeStart;
                return this;
           }
    
           public Builder timeEnd(Integer timeEnd) {
                this.timeEnd = timeEnd;
                return this;
           }
    
           public Builder page(Integer page) {
                this.page = page;
                return this;
           }
    
           public Builder pageSize(Integer pageSize) {
                this.pageSize = pageSize;
                return this;
           }
    
        private String ticketId;
          public Builder ticketId(String ticketId) {
               this.ticketId = ticketId;
               return this;
          }
    
    public ListTicketMessageReq build(){
        return new ListTicketMessageReq(this);
      }
    }

    public static Builder newBuilder() {
        return new Builder();
    }
}
