// Code generated by lark suite oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.lark.oapi.service.drive.v1.model;
import com.lark.oapi.core.response.EmptyData;
import com.lark.oapi.service.drive.v1.enums.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.SerializedName;
import com.lark.oapi.core.annotation.Body;
import com.lark.oapi.core.annotation.Path;
import com.lark.oapi.core.annotation.Query;
import java.io.File;
import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import com.lark.oapi.core.utils.Strings;
import com.lark.oapi.core.response.BaseResponse;
public class RequestDoc {
    @SerializedName("doc_token")
    private String docToken;
    @SerializedName("doc_type")
    private String docType;
    public String getDocToken() {
        return this.docToken;
    }

    public void setDocToken(String docToken) {
        this.docToken = docToken;
    }

    public String getDocType() {
        return this.docType;
    }

    public void setDocType(String docType) {
        this.docType = docType;
    }


// builder 开始
  public RequestDoc(){}

  public RequestDoc(Builder builder){
      this.docToken = builder.docToken;
      this.docType = builder.docType;
  }

    public static class Builder {
        private String docToken;
        private String docType;
        public Builder docToken(String docToken) {
             this.docToken = docToken;
             return this;
        }
    
        public Builder docType(String docType) {
             this.docType = docType;
             return this;
        }
        public Builder docType(com.lark.oapi.service.drive.v1.enums.DocTypeEnum docType) {
             this.docType = docType.getValue();
             return this;
        }
    
    
    public RequestDoc build(){
        return new RequestDoc(this);
      }
    }

    public static Builder newBuilder() {
        return new Builder();
    }
}
